### ISSUE TITLE
how to verify my email

### ISSUE THREAD

**Issue by UPCLJ** [Cloud-CV/EvalAI#2504] opened 2019-12-12 03:09 UTC
when I enter the url:https://evalai.cloudcv.org/ and sign in my account.
There is a dialog box pops up:
Unable to create or select a team.
Please verify your email first!

**Comment by nikochiko** [comment] 2019-12-12 12:41
@UPCLJ when you sign up, you will receive an email like this from `no-reply@cloudcv.org`:

> Hello from EvalAI!
> 
> You're receiving this e-mail because user "UserName" was registered at evalai.cloudcv.org under this e-mail address.
> 
> To verify your registration, please go to https://evalapi.cloudcv.org/api/auth/registration/account-confirm-email/<your_unique_token>/
> 
> Thank you from EvalAI!
> evalai.cloudcv.org

**Comment by Sanji515** [comment] 2019-12-12 12:53
@nikochiko @UPCLJ I think this issue is the case if a user loses verification email without verifying the link then neither user will be able to verify his account nor create a new account with the same email address.

If I'm right then this is the duplicate of #2122

**Comment by ashadhaz** [comment] 2019-12-26 10:34
Is this issue still open? I would like to work on this @nikochiko

**Comment by RishabhJain2018** [comment] 2020-06-07 16:36
Duplicate of #2486, hence closing it.

**Closed by RishabhJain2018** 2020-06-07 16:36 UTC
