### ISSUE TITLE
[code] Create common methods for fetching environment variables 

### ISSUE THREAD

**Issue by nikochiko** [Cloud-CV/EvalAI#2543] opened 2019-12-25 21:03 UTC
#### Current: 
The code for fetching environment variables is repeated in [`remote_submission_worker.py`](https://github.com/Cloud-CV/evalai/blob/master/scripts/workers/remote_submission_worker.py#L28-L31) and [`rl_submission_worker.py`](https://github.com/Cloud-CV/EvalAI/blob/master/scripts/workers/rl_submission_worker.py#L26-L31).
So in the future, if additional environment variables are used, the changes would have to be made in both places.

#### Proposing:
A common mechanism be used to extract / assign them.
#### A possible solution: 
Creating a `class EnvironmentVariables` > fetching the environment variables > binding the variables to the class
<br>
@RishabhJain2018 @Ram81 Please let me know if this can be a good change. I would like to work on this, + a GCI task on this would be cool!

**Comment by RishabhJain2018** [comment] 2020-06-07 16:51
Duplicate of #2542

**Closed by RishabhJain2018** 2020-06-07 16:51 UTC
