### ISSUE TITLE
Broken Link In The "Read The Docs" For EvailAI

### ISSUE THREAD

**Issue by Rubix982** [Cloud-CV/EvalAI#2733] opened 2020-03-27 15:40 UTC
# The Error

The 'Edit On Github' link on the top right at [this link](https://evalai.readthedocs.io/en/latest/contribution.html) leads to a 404 page.

# The Expected Behavior

It leads to a file to edit changes into.

# Observed Behavior

Instead it sends me to a blank page with the text
```
Not Found
```

At [link](https://github.com/Cloud-CV/EvalAI//master/docs/source/contribution.rst)

# Steps to reproduce the issue

Just click on the 'Edit On Github' link at [here](https://evalai.readthedocs.io/en/latest/contribution.html).

# What Operating System / Browser Am I Using

OS is irrevelant here. Browser is Chromium with the version
```
Chromium 80.0.3987.106 Arch Linux
```

# Output of console log

Irrelevant here

Thank you!

( Or just let me know which file it should instead redirect to - I don't know where to exactly make the change to href of the a tag - pretty sure it should lead to [this link instead](https://github.com/Cloud-CV/EvalAI/blob/master/.github/CONTRIBUTING.md). )

**Comment by Rubix982** [comment] 2020-03-27 15:43
This is in reference to an issue, #2560 [Update the Contribution Guidelines on EvalAI-Docs #2560](https://github.com/Cloud-CV/EvalAI/issues/2560) where the User asks the contributing text from which we reach the broken results at the [link]https://evalai.readthedocs.io/en/latest/contribution.html] should be updated with the current and updated contributing at [this link](https://github.com/Cloud-CV/EvalAI/blob/master/.github/CONTRIBUTING.md).

Thanks. <3

**Comment by deshraj** [comment] 2020-04-01 04:19
Duplicate of #2560. Closing it.

**Closed by deshraj** 2020-04-01 04:19 UTC
