### ISSUE TITLE
Redirecting to home page with limited access after sign up

### ISSUE THREAD

**Issue by Kajol-Kumari** [Cloud-CV/EvalAI#2646] opened 2020-01-26 16:52 UTC
Current behaviour:
1. It redirected to the login page after clicking on the signup button.
2. A message which is not so meaningful is shown after the unverified user sign up.
3. Unverified user is not able to access his/her dashboard.

Expected Behaviour:
1. Unverified users should have basic access right of his/her dashboard. 
2. It should have provided a meaningful message after login through a new account why one is "Unable to create or select a team."

Feature to be added:
1. Instead of directing to the login page after signup,it should direct the user to the home page.
2. Give right to access his/her Dashboard to the unverified user with a message to verify their mail in order to get full access right.

screenshort: https://ibb.co/7WfJ2GR

**Comment by nikochiko** [comment] 2020-01-26 17:08
I think this is a duplicate of https://github.com/Cloud-CV/EvalAI/issues/1934

**Comment by Kajol-Kumari** [comment] 2020-01-26 17:14
@nikochiko Yes the email part is same as #1934, i missed to look up on the other's issues.But what about feature part and second part of this issue?

**Comment by nikochiko** [comment] 2020-01-26 17:20
Can you elaborate on why you think it will be better to redirect to the home page?

**Comment by Kajol-Kumari** [comment] 2020-01-26 17:23
After signing up, user don't usually prefer to enter their details again. So it would have been if after signing up, user would have been directed to the home page showing a message telling them to verify their email Id.

**Comment by Suryansh5545** [comment] 2020-01-26 18:35
@nikochiko I think @Kajol-Kumari is saying right. it does make more sense to redirect to home page instead of showing a message with "false" on dashboard when user sign up and also we should redirect the user who log out to landing page or homepage . I have personally feels quite annoying when I am redirected to log in page just after log out.

**Comment by nikochiko** [comment] 2020-01-27 07:00
@Kajol-Kumari Nice point! :100:
I think the philosophy behind redirecting to the login page is this:
-> We don't sign-in the user automatically after filling the details for sign up 
-> So, if the user gets to the homepage first
-> he/she will have to go to the login page anyway in order to sign-in.

(Let me know if I am missing something). 
So if I understand correctly, what you mean is to log in user automatically after signing up, and allow some limited functionality until the user is verified. Is that right?

**Comment by Kajol-Kumari** [comment] 2020-01-27 12:18
yes @nikochiko It would also be better if with limited functionality, a message will be attached to their dashboard telling them to verify their email ID in order to get the full access rights.

**Comment by Suryansh5545** [comment] 2020-01-27 12:23
@Kajol-Kumari @nikochiko I think the limited functionality aspect is already implemented in the form of the error message saying to verify the email .

**Comment by Kajol-Kumari** [comment] 2020-01-27 12:37
@Suryansh5545 I am not sure whether i got your question or not but currently after someone do sign up and login without email verification.That person is not even able to access his/her dashboard.So by limited access i mean to  have access to one's dashboard only showing them the message to complete the verification process till they verify their email.

**Comment by nikochiko** [comment] 2020-01-27 12:38
@Kajol-Kumari Great! Can you open another issue or change the title of this one accordingly then? 
The issue mentioned in the title has been clarified `#1934`. 
Also, could you please add a list of the additions you want to see? We could split the addition into multiple steps. That will make both the contribution and review easier. And also allow anyone new to know about the feature request and provide feedback.

**Comment by nikochiko** [comment] 2020-01-27 12:42
@Suryansh5545 I meant limited functionality as in [allowing an unverified user to view challenge details](https://github.com/Cloud-CV/EvalAI/issues/2241).

**Comment by Suryansh5545** [comment] 2020-01-27 13:27
@nikochiko there is a pr for this ability and it was actually the task of GCI

**Comment by Suryansh5545** [comment] 2020-01-27 13:32
#2640

**Comment by Suryansh5545** [comment] 2020-01-27 13:34
@Kajol-Kumari so you want to show the dashboard with the please verify your email message?

**Comment by Kajol-Kumari** [comment] 2020-01-27 14:01
@Suryansh5545 I want to show the normal dashboard with count of challenges and participants(will always be 0 for new user) and along with that, an attached message telling them to verify their email id to have full access i.e creating host,creating participant,creating challenges etc.

**Comment by Suryansh5545** [comment] 2020-01-27 14:02
> @Suryansh5545 I want to show the normal dashboard with count of challenges and participants(will always be 0 for new user) and along with that, an attached message telling them to verify their email id to have full access i.e creating host,creating participant,creating challenges etc.

Got it

**Comment by Suryansh5545** [comment] 2020-01-27 14:02
@Kajol-Kumari but perhaps I will suggest to get a maintainer advise on this issue

**Comment by nikochiko** [comment] 2020-01-27 14:47
@Suryansh5545 
> 
> @nikochiko there is a pr for this ability and it was actually the task of GCI

I know, I was just giving an example. :)

**Comment by Kajol-Kumari** [comment] 2020-01-27 15:18
@RishabhJain2018 please have a look at the suggestions.

**Comment by RishabhJain2018** [comment] 2020-03-01 03:44
Thanks @Kajol-Kumari , @nikochiko and @Suryansh5545 for the suggestions. I think what you guys are proposing makes sense. I'm summarizing the above suggestions here  - 
1. A new user should be logged-in directly after signup instead of redirecting to login page.
2. The message on the dashboard for verifying the email should be meaningful giving the reason.
3. Even if the email isn't verified, the user should be able to view the challenges.

Please let me know if I missed anything.
Also, would anyone of you like to work on this in three different PR's so that it will be easy for me to review and merge.

**Comment by Kajol-Kumari** [comment] 2020-03-01 05:29
> Thanks @Kajol-Kumari , @nikochiko and @Suryansh5545 for the suggestions. I think what you guys are proposing makes sense. I'm summarizing the above suggestions here -
> 
> 1. A new user should be logged-in directly after signup instead of redirecting to login page.
> 2. The message on the dashboard for verifying the email should be meaningful giving the reason.
> 3. Even if the email isn't verified, the user should be able to view the challenges.
> 
> Please let me know if I missed anything.
> Also, would anyone of you like to work on this in three different PR's so that it will be easy for me to review and merge.

Yes @RishabhJain2018 These are the features we want to add on. Also i would like to work on it and @nikochiko and @Suryansh5545 you people can also work on the same as there are 3 features so will have 3 PRs for this. Please let us know if you have enough time to work on this(As you people have exams going on). Meanwhile, I would like to go with first part i.e Redirecting user to Dashboard with meaningful message.

**Comment by Suryansh5545** [comment] 2020-03-01 05:36
@Kajol-Kumari My exams will be over by 3 march. But I will take a gaming break for a week after my exams so you go ahead.:+1:

**Comment by Kajol-Kumari** [comment] 2020-03-03 11:15
@RishabhJain2018 one thing i would like to add as suggested by @Suryansh5545 that it would be better if we direct the user to home page rather than login page after they logout. Sir, please let me know should i go for it or not.

**Comment by Diaga** [comment] 2020-03-20 11:07
@Kajol-Kumari Hello, I would like to work on this if the issue is open.

**Comment by deshraj** [comment] 2020-06-21 16:43
We discussed about this issue and here is the updated plan:

1. User signs up and haven't verified their email address
2. User tries to login
3. Prevent user from going to the dashboard page and show a prompt that "Please verify your email address first"

Basically, until the user has verified their email address, they won't be go to dashboard. @Kajol-Kumari can we please add this to Frontend V2?

**Closed** 2020-06-27 23:59 UTC
Labels: GSoC-2020, enhancement, frontend, medium-difficulty
