### ISSUE TITLE
[code] Common method to create module level constants for worker files

### ISSUE THREAD

**Issue by nikochiko** [Cloud-CV/EvalAI#2544] opened 2019-12-25 21:20 UTC
#### Currently:
The code to create module level constants like `CHALLENGE_DATA_DIR`, `SUBMISSION_DATA_DIR` is the same for both [`submission_worker.py`](https://github.com/Cloud-CV/EvalAI/blob/master/scripts/workers/submission_worker.py#L56-L72) and [`remote_submission_worker.py`](https://github.com/Cloud-CV/evalai/blob/master/scripts/workers/remote_submission_worker.py#L33-L44). 
It only differs in that they both depend on a temporary base directory, the rest of the directory structure is the same.

#### Proposing:
A common mechanism be used to generate all the module level constants in both files. This way changes will be consistent throughout the codebase.

#### Possible solution:
Create a `class Constants` > generate temporary file > compute corresponding structure > bind these constants to the instance
<br>
@RishabhJain2018 @Ram81 is this addition useful? 
if yes, I would like to work on it :)

**Comment by RishabhJain2018** [comment] 2020-06-07 16:51
Duplicate of #2542

**Closed by RishabhJain2018** 2020-06-07 16:51 UTC
