### ISSUE TITLE
Login through internet returns error: Access has been blocked

### ISSUE THREAD

**Issue by vpozdnyakov** [Cloud-CV/EvalAI#2788] opened 2020-05-09 18:19 UTC
I checked [issue 2434](https://github.com/Cloud-CV/EvalAI/issues/2434), it looks like something different.
- **Expected behaviour**
Login through internet works
- **Observed behaviour**
Error `Access to XMLHttpRequest ... has been blocked by CORS policy`
- **Steps to reproduce the problem**
Open http://competition.pozdn.keenetic.pro/auth/login and try to log in by "admin", "password".
- **Operating system**
Server: Windows 10 Pro 1909
Client: macOS Mojave 10.14.6 (18G4032), Google Chrome 81.0.4044.129
- **Copies of the console/server logs**
I created the following list of domain names on my router (I don't understand which components should be visible on frontend):
![image](https://user-images.githubusercontent.com/12996098/81481599-06ea5380-923a-11ea-8b3f-f9455665c082.png)

I changed the API path in `/frontend/src/js/config.json`:
![image](https://user-images.githubusercontent.com/12996098/81480872-14e9a580-9235-11ea-81ad-420dc870d6e5.png)

I try to log in and get this error:
![image](https://user-images.githubusercontent.com/12996098/81481017-e02a1e00-9235-11ea-95dc-b19bc9404b52.png)

**Comment by deshraj** [comment] 2020-05-12 06:52
Hi @vpozdnyakov, thanks for opening the issue. Since you are trying to run EvalAI on your own private machine, you will have to enable cors. Follow these steps:

1. https://github.com/Cloud-CV/EvalAI/blob/master/settings/prod.py#L17 (set this to `True`)
2. Comment / remove these lines: https://github.com/Cloud-CV/EvalAI/blob/master/settings/prod.py#L19-L23

This should fix your issue. Closing this issue since not related to the active development of EvalAI. Please consider asking questions on our Gitter channel.

**Closed by deshraj** 2020-05-12 06:52 UTC

**Comment by vpozdnyakov** [comment] 2020-05-13 12:51
Hi @deshraj, thanks for your answer. Unfortunately your advice didn't help. Here is absolutely the same problem. I don't exactly understand how these settings work, but I guess my local machine uses the `dev.py` settings where CORS are already enabled (loaded from `common.py`). Could you suggest other options to solve this problem? Or tools/approaches which can help me detect the cause of the problem? Unfortunately I don't have enough experience in WEB and HTTP to solve this problem on my own.

Also I suggest to give an exhaustive description of how to configure EvalAI on the local machine in the documentation.

**Comment by vpozdnyakov** [comment] 2020-05-15 12:51
@deshraj sorry, this problem is related to my DNS service settings. thank you!

**Comment by deshraj** [comment] 2020-05-18 05:39
Sorry @vpozdnyakov I was occupied with other stuff. Glad that the issue is resolved on your side.
