### ISSUE TITLE
UI-issues in Mobile.

### ISSUE THREAD

**Issue by Tanuj22** [Cloud-CV/EvalAI#2599] opened 2020-01-08 18:20 UTC
The Topbar options and and Logout botton are not showing as expected in Mobile View.

![Screenshot from 2020-01-08 23-38-38](https://user-images.githubusercontent.com/42486853/72004285-15ffcb80-3271-11ea-9536-54de3915f4a1.png)

Can i work on this?

**Comment by Suryansh5545** [comment] 2020-01-09 02:47
@Tanuj22 This is the duplicate of #2553 and there is a PR to close this #2563

**Closed** 2020-01-10 13:23 UTC
