### ISSUE TITLE
Error in Running EvalAI

### ISSUE THREAD

**Issue by aayusharora** [Cloud-CV/EvalAI#1282] opened 2017-09-26 14:01 UTC
After the last Merge, the project is not able to work locally.
![screen shot 2017-09-26 at 7 29 17 pm](https://user-images.githubusercontent.com/12194719/30864437-365d657a-a2f1-11e7-9529-ffee7744803c.png)

**Comment by RishabhJain2018** [comment] 2017-09-26 14:03
@aayusharora Please update your dev.py file with `dev.sample.py` specifically the `INSTALLED APPS` section. I hope it will solve the issue.

**Comment by RishabhJain2018** [comment] 2017-09-26 14:16
@aayusharora I think the issue is resolved. Hence I am closing this. Please reopen if the problem still persists.

**Closed by RishabhJain2018** 2017-09-26 14:16 UTC
