### ISSUE TITLE
Insecure requirement: uWSGI

### ISSUE THREAD

**Issue by nikochiko** [Cloud-CV/EvalAI#2505] opened 2019-12-12 13:17 UTC
#### Description of the issue:
The version of uWSGI used by EvalAI (2.0.15) is insecure and should be updated to 2.0.18 
See: https://requires.io/github/Cloud-CV/EvalAI/requirements/?branch=master
![uWSGI-insecure](https://user-images.githubusercontent.com/37668193/70715171-ba90fb00-1d0f-11ea-9977-8d873e7522d2.PNG)

#### How to resolve:
1. Update package on your branch
2. Make API changes if any
3. Make a PR and fix Travis-CI failures
4. Test it and update the code if possible

**Comment by veb7vmehra** [comment] 2019-12-12 14:30
Do I only need to update this particular library on mine branch and make a pull request to close this issue?
I am willing to contribute for this organization and also new here so just asking to confirm..

**Comment by veb7vmehra** [comment] 2019-12-12 15:59
Do I only need to update this particular package on mine branch and make a pull request to close this issue?
I am willing to contribute for this organization and also new here so just asking to confirm..

**Comment by nikochiko** [comment] 2019-12-14 07:29
@veb7vmehra Please wait for one of the project maintainers to respond. Then they can decide if this is required and assign the task. 
But this should be the basic steps:
1. Update package on your branch
2. Make API changes if any
3. Make a PR and fix Travis-CI failures
4. Test it and update the code if possible

**Comment by RishabhJain2018** [comment] 2020-06-07 16:41
Duplicate of #2564

**Closed by RishabhJain2018** 2020-06-07 16:41 UTC
