### ISSUE TITLE
pip install -r requirements/dev.txt breaks

### ISSUE THREAD

**Issue by anweshknayak** [Cloud-CV/EvalAI#399] opened 2017-01-10 10:36 UTC
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-YodbBn/twisted/

**Comment by anweshknayak** [comment] 2017-01-10 10:38
Faced this while running a fresh install on different Ubuntu 14.04 PC.

**Comment by deshraj** [comment] 2017-01-10 10:38
Can you please post a screenshot ?

**Comment by anweshknayak** [comment] 2017-01-10 10:40
![screenshot from 2017-01-10 16 10 02](https://cloud.githubusercontent.com/assets/8139783/21803243/3d5d3210-d74f-11e6-8841-935588f4a09a.png)

**Comment by RishabhJain2018** [comment] 2017-01-10 10:54
@anweshknayak Please try this [link](http://stackoverflow.com/questions/35991403/python-pip-install-gives-command-python-setup-py-egg-info-failed-with-error-c). May be the setuptools are not upgraded.

**Comment by anweshknayak** [comment] 2017-01-10 11:03
Tried that too before. Doesn't work

**Comment by deshraj** [comment] 2017-01-10 21:24
@anweshknayak please update the python version to solve this problem.

**Comment by deshraj** [comment] 2017-01-11 13:14
I think the issue is solved now. Closing it. Please feel free to reopen if you are still facing this problem.

**Closed by deshraj** 2017-01-11 13:14 UTC

**Comment by anweshknayak** [comment] 2017-01-20 10:17
refer this for solving (http://stackoverflow.com/questions/22938679/error-trying-to-install-postgres-for-python-psycopg2)
