### ISSUE TITLE
email confirmation page links back to main hosted instance

### ISSUE THREAD

**Issue by ezavesky** [Cloud-CV/EvalAI#1619] opened 2018-04-01 12:54 UTC
After clicking/processing an email confirmation link, the resultant page links back to the main/cloud instance instead of the localhost/docker instance that is running the page.

1. Sign up as a new user
2. Click the confirmation link
3. The page from `http://localhost:8000/api/auth/email-confirmed/` contains a button to proceed to **login**, but when clicked it goes to the main URL `https://evalai.cloudcv.org/auth/login` instead.

Low priority, but may cause some issue when used locally via docker/source.

**Comment by deshraj** [comment] 2018-04-02 03:27
Thanks, @ezavesky for opening this issue. This is just a static page shown to the participants when they confirm their email. Currently, it is being served by the backend server and it needs to be changed to be handled by angular routing. I am increasing the priority of this issue so that we get it resolved really soon. Sorry for the inconvenience.

**Comment by ezavesky** [comment] 2018-04-02 14:45
@deshraj Thanks for the hustle.  These are minor issues, IMO and the availability of the project is still a fantastic open source contribution! I will continue to report issues (if more exist) and hope to give back where I can.

**Comment by deshraj** [comment] 2018-04-02 20:28
Thanks a lot. We look forward to hearing more about the project.

**Comment by 123vivekr** [comment] 2018-07-17 08:06
I am a newbie in this project. Can I work on this?

**Comment by deshraj** [comment] 2018-07-17 08:07
Sure @123vivekr. Go ahead. :)

**Comment by 123vivekr** [comment] 2018-07-17 16:32
I have gone through the source a couple of times. I am confused on how to route to the angular log-in page through back-end Django function?

**Comment by darthgera123** [comment] 2018-09-01 16:57
Hi is this issue still open, else can i work on this?

**Comment by RishabhJain2018** [comment] 2019-02-02 22:08
This issue is still open to work :)

**Comment by ashish0910** [comment] 2019-02-03 14:37
@RishabhJain2018 can I work on this ?

**Comment by RishabhJain2018** [comment] 2019-02-03 19:05
Sure @ashish0910 you can work on this!

**Comment by namish800** [comment] 2019-02-14 18:38
Is this issue still open can I work on this? @RishabhJain2018

**Comment by RishabhJain2018** [comment] 2019-02-14 18:41
@ashish0910 Any updates on this?

**Comment by ashish0910** [comment] 2019-02-15 04:03
@namish800 you can also work on it , I am having hard time resolving it . @RishabhJain2018

**Comment by anuj-rathore** [comment] 2019-02-19 22:41
Can I work on this?

**Comment by RishabhJain2018** [comment] 2019-02-19 22:43
@anuj-rathore You can work on this. I'm not sure if @namish800 is working on it.

**Comment by anuj-rathore** [comment] 2019-02-19 22:46
@RishabhJain2018 I tried replicating the issue, for me after clicking on the Login button on [http://localhost:8000/api/auth/email-confirmed/], It took me to the login page!

Seems like it already been fixed!

**Comment by anuj-rathore** [comment] 2019-02-19 22:54
I have checked it on localhost and original site: [https://evalai.cloudcv.org/auth/login].
It is working as expected, I think we should close this issue.

**Comment by RishabhJain2018** [comment] 2019-02-19 23:00
No, this is not fixed. Currently what happens is that after creating a new user on `localhost` and verifying on `http://localhost:8000/api/auth/email-confirmed/`, the Login button redirects the user to the main hosted instance i.e. `https://evalai.cloudcv.org/auth/login` which should not be the case. It should be redirected to `http://localhost:8888/auth/login`.

Please let me know if something is not clear.

**Comment by anuj-rathore** [comment] 2019-02-19 23:09
Sorry, I missed the url, taking this issue!

**Comment by Ayukha** [comment] 2019-02-19 23:18
@RishabhJain2018  This is because the URL has been hardcoded [here](https://github.com/Cloud-CV/EvalAI/blob/master/apps/accounts/templates/account/email_confirm.html/#L45).
Can't we fix this by checking the `DEBUG` in settings and passing the url in context accordingly instead of changing it to angular routing?

**Comment by anuj-rathore** [comment] 2019-02-19 23:37
I was thinking of a hacky solution just hardcode: 
**From:**
<a href="https://evalai.cloudcv.org/auth/login" class="waves-effect waves-dark btn ev-btn-dark blue-grey darken-4">Log In</a>
**To**
<a href=" http://localhost:8888/auth/login" class="waves-effect waves-dark btn ev-btn-dark blue-grey darken-4">Log In</a>
This will work fine.

Actually, the issue is with the port, earlier it was 8000 and now it is 8888

What do you think, should I hard code and move on, or try to resolve the issue with the confirmation mail and the docker?

**Comment by anuj-rathore** [comment] 2019-02-20 00:29
@RishabhJain2018, Should I proceed by making changes in docker?

**Comment by yashdusing** [comment] 2019-02-20 16:01
@anuj-rathore Instead of doing this through plain HTML hardcoding you could try doing it in the javascript. This way you don't have to hardcode the port and the setup would work on any port.

**Comment by namish800** [comment] 2019-02-20 16:04
@anuj-rathore I am working on this issue.

**Comment by anuj-rathore** [comment] 2019-02-20 17:14
@namish800, since you are working, if you need any help we can discuss

**Comment by krishnadey30** [comment] 2019-03-13 23:02
@RishabhJain2018 I think we should make it dynamic.
I checked this and its working

`<a id="krishna" class="waves-effect waves-dark btn ev-btn-dark blue-grey darken-4">Log In</a>`

```
<script type="text/javascript">
        var a = document.getElementById('krishna');
        a.href = window.location.protocol+"//"+window.location.href.split('/')[2]+"/auth/login";
</script>
```

**Comment by krishnadey30** [comment] 2019-03-13 23:02
@RishabhJain2018 If no one is working in it. I can take it up.

**Comment by Ayukha** [comment] 2019-03-26 06:48
@RishabhJain2018 I have fixed this issue, can I open a PR for it?

**Comment by galipremsagar** [comment] 2019-03-26 07:14
@Ayukha  Have a look at this article on which email clients support & restrict js execution on their end. Did you test it on Gmail only or even on other email clients?

**Comment by RishabhJain2018** [comment] 2019-03-27 00:36
Sure! @Ayukha.

**Comment by Suryansh5545** [comment] 2020-01-14 15:17
@RishabhJain2018 If this issue is still open can i work on it?

**Closed** 2020-06-16 05:23 UTC
Labels: GSOC-2019, backend, critical, enhancement, frontend, good first issue, medium-difficulty
