### ISSUE TITLE
No module named 'rest_framework_simplejwt' error on running after latest master pull

### ISSUE THREAD

**Issue by burnerlee** [Cloud-CV/EvalAI#3176] opened 2021-01-26 11:08 UTC
Error:
```
worker_1     | wait-for-it.sh: timeout occurred after waiting 45 seconds for django:8000
worker_1     | Traceback (most recent call last):
worker_1     |   File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
worker_1     |     "__main__", mod_spec)
worker_1     |   File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
worker_1     |     exec(code, run_globals)
worker_1     |   File "/code/scripts/workers/submission_worker.py", line 43, in <module>
worker_1     |     django.setup()
worker_1     |   File "/usr/local/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
worker_1     |     apps.populate(settings.INSTALLED_APPS)
worker_1     |   File "/usr/local/lib/python3.7/site-packages/django/apps/registry.py", line 91, in populate
worker_1     |     app_config = AppConfig.create(entry)
worker_1     |   File "/usr/local/lib/python3.7/site-packages/django/apps/config.py", line 116, in create
worker_1     |     mod = import_module(mod_path)
worker_1     |   File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
worker_1     |     return _bootstrap._gcd_import(name[level:], package, level)
worker_1     |   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
worker_1     |   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
worker_1     |   File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
worker_1     | ModuleNotFoundError: No module named 'rest_framework_simplejwt'
```

**Comment by Ram81** [comment] 2021-01-26 11:09
@burnerlee you have to rebuild the docker containers. New packages were added recently.

**Comment by Ram81** [comment] 2021-01-26 12:14
Closing this as it is not a bug.

**Closed by Ram81** 2021-01-26 12:14 UTC

**Comment by burnerlee** [comment] 2021-01-26 12:18
Yes, worked! Thank you @Ram81 :)
