### ISSUE TITLE
fix submission worker error : 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by nadzma** [Cloud-CV/EvalAI#2254] opened 2019-04-02 13:44 UTC
@RishabhJain2018  Although the challenge is active and approved and the worker is restarted I have the error message after submitting.  ERROR Exception while receiving message from submission queue with error 'NoneType' object has no attribute 'get'

<img width="1334" alt="Capture d’écran 2019-04-02 à 11 55 23" src="https://user-images.githubusercontent.com/33626402/55407340-163e9e00-555e-11e9-8815-02a689400c22.png">

**Comment by christianabbet** [comment] 2019-04-04 10:03
I have the same problem here. I tired to look at the `submission_worker.py`. It seams that `PHASE_ANNOTATION_FILE_NAME_MAP` does not contain matching challenge_id/phase_id in the dictionary.

**Comment by nadzma** [comment] 2019-04-04 10:05
@christianabbet  Did you manage to solve it ?

**Comment by christianabbet** [comment] 2019-04-04 10:08
Unfortunately no...
I will let you know if I find anything. Please let me know as well if you managed to solve the issue

**Comment by nadzma** [comment] 2019-04-04 10:13
okey . This is a new bug . It used to work two weeks ago .

**Comment by nadzma** [comment] 2019-04-04 11:06
@christianabbet  can we refer to someone from the cloud-cv team  to help us ?

**Comment by kurianbenoy** [comment] 2019-04-04 16:53
> @RishabhJain2018 Although the challenge is active and approved and the worker is restarted I have the error message after submitting. ERROR Exception while receiving message from submission queue with error 'NoneType' object has no attribute 'get'
> 
> <img alt="Capture d’écran 2019-04-02 à 11 55 23" width="1334" src="https://user-images.githubusercontent.com/33626402/55407340-163e9e00-555e-11e9-8815-02a689400c22.png">

Can you please say the steps to reproduce this issue @nadzma. I am not getting a similar error, also is it a duplicate of #2202. Can you be specific which challenge were you trying to create and for any doubts refer [docs ](https://evalai.readthedocs.io/en/latest/challenge_creation.html)

**Comment by nadzma** [comment] 2019-04-05 09:04
@kurianbenoy  I am usinf the evalai starter challenge and I am using the latest version of evalai and I am referring to the docs to create a challenge ; But after restarting the worker and submitting a solution I got this error of Attribute Error 'NonType' object

**Comment by nadzma** [comment] 2019-04-08 10:04
@christianabbet  Hey did you manage to fix this bug ? I am tried several solution but unfortunately I couldn't fix it

**Comment by christianabbet** [comment] 2019-04-08 14:50
@nadzma I went back to a previous commit. I think it was the easiest way to continue working on the project.

**Comment by nadzma** [comment] 2019-04-09 08:26
@christianabbet   which version is working well (especially the submission worker) ?

**Comment by christianabbet** [comment] 2019-04-09 08:55
@nadzma I reverted to repo to the commit : https://github.com/Cloud-CV/EvalAI/commit/fff5f40a9ec0dab3fed6a429edea69b10c621ae6. The submission worker are working well for me

**Comment by nadzma** [comment] 2019-04-09 13:18
@christianabbet   Unfortunately It doesn't work too

**Comment by RishabhJain2018** [comment] 2019-04-09 17:51
@nadzma Let's discuss it on the Gitter channel tomorrow at the proposed time. I hope that'll resolve the issue.

**Comment by RishabhJain2018** [comment] 2019-04-09 17:51
Hence, I'm closing this.

**Closed by RishabhJain2018** 2019-04-09 17:51 UTC
