### ISSUE TITLE
Failure to create competition

### ISSUE THREAD

**Issue by mlandry22** [Cloud-CV/EvalAI#1390] opened 2017-12-01 19:29 UTC
When I try to create a new challenge by uploading a zip file, I get red warning messages and no evidence that a competition was created.
I started using the examples in this repo and then used the one at 
https://github.com/Cloud-CV/EvalAI-Examples
Depending on which one I was using, I would get a message about having no scoring file, 2 YAML files, or a blank message.

These are the console logs for the blank messages received with the example repository file:
```
[2017-11-30 20:40:01] INFO "OPTIONS /api/hosts/challenge_host_team/ HTTP/1.1" 200 0
[2017-11-30 20:40:01] INFO "GET /api/hosts/challenge_host_team/ HTTP/1.1" 200 345
[2017-11-30 20:40:21] WARNING "POST /api/challenges/challenge/challenge_host_team/2/zip_upload/ HTTP/1.1" 400 75714
```

I also tried the same process with the public site and received the warning about 2 yaml files present. I tried to rename the file in case it was conflicting with the existing DB and still received the same error. There are not 2 YAML files in the zip file.

The seeded Kathleen Challenge competition did work (though I cannot upload a submission, but that's a separate issue).

Mac Sierra 10.12.6 with brew
postgres 10.1
rabbitmq/3.6.14
virtualenv-15.1.0
current clone of EvalAI

**Comment by deshraj** [comment] 2017-12-01 22:41
Hi @mlandry22, sorry for the inconvenience. I was working on solving the issue and I am pretty much done here #1369 but I could not finish it due to paper submission deadlines. I will fix it and get it merged into the master by this weekend. 

Please let us know if you face some other issues. We can discuss and solve those errors quickly.

**Comment by mlandry22** [comment] 2017-12-01 22:56
Oh, great. Ok, that's exciting.

If you think that being able to submit a file is related to that Issue, I'll not worry about that. If you think it is a separate Issue, let me know and I'll log it accordingly. Behavior is that the browser does not let you click on any files--it seems as if it's searching for a particular type, but standard ones do not work.
We'd love to use EvalAI for a conference hackathon next week. Is that too ambitious (I expect the scoring file to be difficult, but can hopefully work through that)?
Either way, thanks for the response @deshraj

**Comment by deshraj** [comment] 2017-12-01 23:29
> If you think that being able to submit a file is related to that Issue, I'll not worry about that. If you think it is a separate Issue, let me know and I'll log it accordingly. Behavior is that the browser does not let you click on any files--it seems as if it's searching for a particular type, but standard ones do not work.

@mlandry22 Yeah I am pretty sure that this is the error. I will fix it asap. 

> We'd love to use EvalAI for a conference hackathon next week. Is that too ambitious (I expect the scoring file to be difficult, but can hopefully work through that)?

That's great. We would be more than happy to host it on EvalAI. Would you mind sending some details about the hackathon over email to team@cloudcv.org?  Also, please let me know if you want to talk about hosting the challenge, I would be happy to talk to you about skype/hangouts. You can reach me out personally at deshraj@gatech.edu

**Comment by RishabhJain2018** [comment] 2018-01-17 12:23
Hi @mlandry22 Apologies for replying so late. We have fixed the feature of creating the challenge using zip file. Now you can easily host your challenge. Please try using the same repository as you were using earlier(https://github.com/Cloud-CV/EvalAI-Examples). Also, if you still come across some issues feel free to reach to us.

**Comment by deshraj** [comment] 2018-02-11 22:29
@mlandry22: the issue is fixed now. Please let us know if you still face the error in creating a challenge. We will be happy to help you. :)

**Closed by deshraj** 2018-02-11 22:29 UTC
