### ISSUE TITLE
[Error Display] User logs in and email not verified.

### ISSUE THREAD

**Issue by pushkalkatara** [Cloud-CV/EvalAI#2486] opened 2019-11-24 08:14 UTC
- the expected behavior
Users should be asked to verify email first to start using EvalAI.
- the observed behavior
The message displayed is unable to create or select a team, and unknown comment as false as in the image
![unable](https://user-images.githubusercontent.com/21266230/69491814-5ae9c180-0ec0-11ea-80cf-1a6b68dbdb64.png)

- steps to reproduce the problem
1. Register a new account.
2. Login using the account without verifying.

**Comment by bismitaguha** [comment] 2019-11-24 12:05
Can I work on this issue @pushkalkatara ?

**Comment by vs74** [comment] 2019-11-24 12:24
@pushkalkatara, is the problem observed on your local machine ? The reason I am asking is that user email and login are verified on the official website [here](https://evalai.cloudcv.org)

**Comment by pushkalkatara** [comment] 2019-11-24 12:44
Yes i observed it on local host, in the terminal we get a link through which we can verify the account locally, but before that if user tries to login, the above error occurs.

**Comment by pushkalkatara** [comment] 2019-11-24 12:45
@bismitaguha EvalAI maintainers can only assign the issues.

**Comment by bismitaguha** [comment] 2019-11-25 11:01
@RishabhJain2018 can I work on this?

**Comment by Akash16s** [comment] 2019-12-10 05:45
@RishabhJain2018 can I work on this issue

**Comment by gautamjajoo** [comment] 2019-12-10 13:18
@pushkalkatara There was an issue https://github.com/Cloud-CV/EvalAI/issues/1337 and a PR https://github.com/Cloud-CV/EvalAI/pull/2152 for it and was closed due to inactivity

**Comment by RishabhJain2018** [comment] 2020-06-07 16:42
Duplicate of #2504

**Closed by RishabhJain2018** 2020-06-07 16:42 UTC
