### ISSUE TITLE
Outdated zip_challenge.yml leads to creation of challenge that is already expired

### ISSUE THREAD

**Issue by nikhilmudholkar** [Cloud-CV/EvalAI#2092] opened 2019-02-08 18:55 UTC
EvalAI takes metadata from zip_challenge.yaml file inside the test_zip_folder to create a new challenge. The start and end dates in the .yaml file are outdated. So if a new user when tries to create a new challenge, the challenge is already over when created. This creates a lot of issues, particularly while submission.

Deliverables:-
- Update the dates in zip_challenge.yml

**Comment by kurianbenoy** [comment] 2019-03-06 15:04
Duplicate of #2151

**Closed** 2019-06-15 09:33 UTC
Labels: inactivity
